name: flutter_clean_architecture_with_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
 
dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter  
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  go_router: ^13.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
